import type { Message } from '@/types';

/**
 * Format chat history as portable Markdown for export / share.
 */
export function chatToMarkdown(messages: Message[], subjectLabel: string, agentName: string): string {
  const header = `# Ustaad.ai — ${subjectLabel} Session\n\n_Tutor: ${agentName}_\n_Exported: ${new Date().toLocaleString('en-PK')}_\n\n---\n\n`;

  const body = messages
    .filter((m) => m.text.trim().length > 0)
    .map((m) => {
      const speaker = m.role === 'user' ? '**🧑‍🎓 Student**' : `**🎓 ${agentName}**`;
      const time = m.timestamp ? m.timestamp.toLocaleTimeString('en-PK', { hour: '2-digit', minute: '2-digit' }) : '';
      const imageNote = m.imageBase64 ? '\n\n_[Image attached]_' : '';
      return `### ${speaker} · ${time}\n\n${m.text}${imageNote}`;
    })
    .join('\n\n---\n\n');

  const footer = `\n\n---\n\n_Generated by [Ustaad.ai](https://ustaad.ai) — Pakistan ka apna AI tutor 🇵🇰_`;

  return header + body + footer;
}

/**
 * Try the native share sheet (mobile, supports WhatsApp), fall back to clipboard.
 * Returns 'shared' | 'copied' | 'failed'.
 */
export async function shareChat(markdown: string, subjectLabel: string): Promise<'shared' | 'copied' | 'failed'> {
  const shareData = {
    title: `Ustaad.ai — ${subjectLabel} chat`,
    text: markdown,
  };

  try {
    if (typeof navigator !== 'undefined' && 'share' in navigator && navigator.canShare?.(shareData)) {
      await navigator.share(shareData);
      return 'shared';
    }
  } catch (err) {
    // user dismissed or share failed; try clipboard
    console.warn('[share] navigator.share failed, falling back to clipboard:', err);
  }

  try {
    await navigator.clipboard.writeText(markdown);
    return 'copied';
  } catch (err) {
    console.error('[share] clipboard failed:', err);
    return 'failed';
  }
}

/**
 * Trigger a download of the markdown as a .md file.
 */
export function downloadMarkdown(markdown: string, subjectLabel: string) {
  const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `ustaad-${subjectLabel.toLowerCase().replace(/\s+/g, '-')}-${new Date().toISOString().slice(0, 10)}.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
